### ISSUE TITLE
Add geospatial libraries to the notbooks

### ISSUE THREAD

**Issue by RobinL** [ministryofjustice/analytics-platform-jupyter-notebook#12]
Need to install GDAL, possibly using `apt-get install python3-gdal`
and libspatial:
https://github.com/libspatialindex/libspatialindex/wiki/1.-Getting-Started possibly `apt-get libspatialindex-dev`

**Comment by damacus** [comment]
gdal-bin and libspatialindex-dev

 are both now part of all the images
