### ISSUE TITLE
jupyter/datascience-notebook: `docker build` fails

### ISSUE THREAD

**Issue by xoen** [ministryofjustice/analytics-platform-jupyter-notebook#28]
Some of the AP team tried to build the `jupyter/datascience-notebook` image locally but we're getting an error from `conda install`.

Exact package causing the error varied but error is something like:

```
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::appdirs-1.4.3-py_1'.
FileNotFoundError(2, "No such file or directory: '/opt/conda/bin/python3.7'")
Attempting to roll back.
```

Base image is pinned but this may be caused by some changes upstream (in the `conda-forge` repository) and/or by the fact that base image is a bit old and conda tries to upgrade some of the packages but then fails.

Something to eventually investigate and fix.

**Comment by xoen** [comment]
As a test I tried to unpin the version of the base image (currently `FROM jupyter/datascience-notebook:14fdfbf9cfc1`) to see if it helped with the problem and it seems like the `conda install` step now runs fine and it progressed to the next step.

**Comment by damacus** [comment]
Closing as I've updated the data science notebook with tests and they're all passing as is.
